<template>
  <div class="system-shell dev-theme">
    <aside v-if="projectId">
      <div class="system-head"><router-link to="/portal">← Portal</router-link><span>DELIVERY</span></div>
      <router-link class="system-brand" to="/devcenter"><span>DC</span><div><b>DevCenter</b><small>Application Delivery</small></div></router-link>
      <div v-if="projectId" class="project-context"><small>ACTIVE PROJECT</small><b>Project #{{projectId}}</b></div>
      <p class="nav-label">Delivery workspace</p>
      <nav>
        <router-link v-for="item in menu" :key="item.path" :to="item.path"><i>{{item.icon}}</i>{{item.name}}</router-link>
      </nav>
      <div class="boundary-note"><b>Delivery boundary</b><p>环境、集群、Namespace 与 Registry 均由 Project Center 提供。</p></div>
    </aside>
    <main :class="{ standalone: !projectId }"><header><div class="header-title"><small>DEVCENTER</small><h2>{{title}}</h2></div><div class="header-actions"><router-link v-if="!projectId" class="switch" to="/portal">← Portal</router-link><router-link class="switch secondary-switch" to="/project-center">Open Project Center →</router-link><CurrentUserMenu/></div></header><div class="content"><router-view/></div></main>
  </div>
</template>
<script setup lang="ts">
import{computed}from'vue';import{useRoute}from'vue-router';import CurrentUserMenu from '../components/common/CurrentUserMenu.vue';const route=useRoute();const projectId=computed(()=>Number(route.params.projectId||route.params.id)||0);const base=computed(()=>projectId.value?`/devcenter/projects/${projectId.value}`:'/devcenter');const menu=computed(()=>projectId.value?[{name:'Overview',path:base.value,icon:'⌂'},{name:'Applications',path:`${base.value}/applications`,icon:'◇'},{name:'CI/CD',path:`${base.value}/pipelines`,icon:'↯'},{name:'Releases',path:`${base.value}/releases`,icon:'↗'},{name:'Runtime',path:`${base.value}/runtime`,icon:'◉'},{name:'Logs',path:`${base.value}/logs`,icon:'≡'}]:[{name:'Projects',path:'/devcenter/projects',icon:'▦'}]);const title=computed(()=>String(route.meta.title||'Application delivery'));
</script>
<style scoped>
.system-shell{min-height:100vh;background:var(--theme-bg)}aside{position:fixed;inset:0 auto 0 0;width:252px;padding:18px 14px;background:#111a2b;border-right:1px solid #29354c;display:flex;flex-direction:column;z-index:10}.system-head{display:flex;justify-content:space-between;align-items:center;padding:0 7px 18px;border-bottom:1px solid #29354c}.system-head a,.system-head span{font-size:10px;color:#8492aa;text-decoration:none}.system-head span{letter-spacing:1.2px}.system-brand{display:flex;gap:11px;align-items:center;padding:22px 7px;color:#f4f6fb;text-decoration:none}.system-brand>span{width:39px;height:39px;display:grid;place-items:center;border-radius:11px;background:linear-gradient(145deg,#6366f1,#4338ca);font-size:11px;font-weight:800}.system-brand b,.system-brand small{display:block}.system-brand b{font-size:15px}.system-brand small{font-size:10px;color:#8492aa;margin-top:3px}.project-context{padding:11px;margin:0 3px 14px;border:1px solid #2e3b55;border-radius:9px;background:#162139}.project-context small,.project-context b{display:block}.project-context small{font-size:9px;color:#74839d;letter-spacing:1px}.project-context b{font-size:11px;margin-top:4px;color:#c9d0e0}.nav-label{font-size:10px;letter-spacing:1.2px;text-transform:uppercase;color:#5e6e89;margin:8px 9px}nav{display:grid;gap:3px}nav a{height:40px;padding:0 10px;border-radius:8px;display:flex;align-items:center;gap:10px;color:#8e9bb1;text-decoration:none;font-size:12px}nav a:hover{background:#172238;color:#edf0f8}nav a.router-link-exact-active{background:rgba(99,102,241,.16);color:#aaa9ff}nav i{width:18px;text-align:center;font-style:normal}.boundary-note{margin-top:auto;padding:14px;border:1px solid #29354c;border-radius:10px;background:#151f33}.boundary-note b{font-size:11px;color:#c7cee0}.boundary-note p{font-size:10px;line-height:1.6;color:#7e8da8;margin:5px 0 0}.system-shell>main{margin-left:252px}.system-shell>main>header{height:68px;padding:0 34px;display:flex;align-items:center;justify-content:space-between;border-bottom:1px solid var(--border-soft);background:var(--theme-panel);position:sticky;top:0;z-index:8}.system-shell header small{font-size:9px;letter-spacing:1.3px;color:#818cf8}.system-shell header h2{font-size:15px;margin:3px 0 0}.switch{padding:8px 11px;border:1px solid var(--border-soft);border-radius:8px;color:var(--muted);font-size:11px;text-decoration:none}.content :deep(.page-content){padding-top:30px}
.system-shell>main.standalone{margin-left:0}.header-title,.header-actions{min-width:0}.header-actions{display:flex;align-items:center;justify-content:flex-end;flex-wrap:wrap;gap:8px}
@media(max-width:900px){.system-shell>main>header{height:auto;min-height:68px;padding:10px 18px}.secondary-switch{display:none}}
</style>
