apiVersion: v1
kind: Service
metadata:
  name: devops-platform-backend
  namespace: devops-platform
spec:
  selector:
    app: devops-platform-backend
  ports:
    - name: http
      port: 5000
      targetPort: 5000

