"""initial enterprise schema

Revision ID: 41cd04839773
Revises: 
Create Date: 2026-07-01 22:31:53.154269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41cd04839773'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('repo_url', sa.String(length=500), nullable=False),
    sa.Column('branch', sa.String(length=120), nullable=False),
    sa.Column('language', sa.String(length=30), nullable=True),
    sa.Column('framework', sa.String(length=50), nullable=True),
    sa.Column('build_type', sa.String(length=30), nullable=True),
    sa.Column('deploy_type', sa.String(length=30), nullable=True),
    sa.Column('image_name', sa.String(length=300), nullable=True),
    sa.Column('image_tag', sa.String(length=100), nullable=True),
    sa.Column('namespace', sa.String(length=120), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('application_spec', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('pipeline_executions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('pipeline_run_name', sa.String(length=253), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('logs', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pipeline_run_name')
    )
    with op.batch_alter_table('pipeline_executions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pipeline_executions_application_id'), ['application_id'], unique=False)

    op.create_table('release_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('release_type', sa.String(length=20), nullable=False),
    sa.Column('environment', sa.String(length=30), nullable=False),
    sa.Column('git_repo', sa.String(length=500), nullable=False),
    sa.Column('git_branch', sa.String(length=120), nullable=False),
    sa.Column('git_commit', sa.String(length=64), nullable=True),
    sa.Column('image_name', sa.String(length=300), nullable=False),
    sa.Column('image_tag', sa.String(length=120), nullable=False),
    sa.Column('pipeline_run_name', sa.String(length=253), nullable=True),
    sa.Column('deploy_namespace', sa.String(length=120), nullable=False),
    sa.Column('deploy_status', sa.String(length=30), nullable=False),
    sa.Column('deploy_user', sa.String(length=120), nullable=False),
    sa.Column('source_release_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['source_release_id'], ['release_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('release_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_release_records_application_id'), ['application_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_release_records_environment'), ['environment'], unique=False)
        batch_op.create_index(batch_op.f('ix_release_records_pipeline_run_name'), ['pipeline_run_name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('release_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_release_records_pipeline_run_name'))
        batch_op.drop_index(batch_op.f('ix_release_records_environment'))
        batch_op.drop_index(batch_op.f('ix_release_records_application_id'))

    op.drop_table('release_records')
    with op.batch_alter_table('pipeline_executions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pipeline_executions_application_id'))

    op.drop_table('pipeline_executions')
    op.drop_table('applications')
    op.drop_table('projects')
    # ### end Alembic commands ###
