"""add approval workflow

Revision ID: b2ea64f02095
Revises: dbf83f90789f
Create Date: 2026-07-01 23:06:21.603710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2ea64f02095'
down_revision = 'dbf83f90789f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approval_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('environment', sa.String(length=30), nullable=False),
    sa.Column('namespace', sa.String(length=120), nullable=False),
    sa.Column('image_name', sa.String(length=300), nullable=False),
    sa.Column('image_tag', sa.String(length=120), nullable=False),
    sa.Column('git_branch', sa.String(length=120), nullable=True),
    sa.Column('git_commit', sa.String(length=64), nullable=True),
    sa.Column('applicant', sa.String(length=120), nullable=False),
    sa.Column('approver', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('pipeline_run_name', sa.String(length=253), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('approval_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_approval_records_application_id'), ['application_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_approval_records_environment'), ['environment'], unique=False)
        batch_op.create_index(batch_op.f('ix_approval_records_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('approval_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_approval_records_status'))
        batch_op.drop_index(batch_op.f('ix_approval_records_environment'))
        batch_op.drop_index(batch_op.f('ix_approval_records_application_id'))

    op.drop_table('approval_records')
    # ### end Alembic commands ###
