"""add environment and configuration centers

Revision ID: dbf83f90789f
Revises: 41cd04839773
Create Date: 2026-07-01 22:53:57.444624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbf83f90789f'
down_revision = '41cd04839773'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application_environments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('environment_name', sa.String(length=30), nullable=False),
    sa.Column('display_name', sa.String(length=80), nullable=True),
    sa.Column('cluster_name', sa.String(length=120), nullable=True),
    sa.Column('kube_context', sa.String(length=200), nullable=True),
    sa.Column('namespace', sa.String(length=120), nullable=False),
    sa.Column('replicas', sa.Integer(), nullable=False),
    sa.Column('image_registry', sa.String(length=300), nullable=True),
    sa.Column('ingress_domain', sa.String(length=300), nullable=True),
    sa.Column('cpu_request', sa.String(length=30), nullable=True),
    sa.Column('cpu_limit', sa.String(length=30), nullable=True),
    sa.Column('memory_request', sa.String(length=30), nullable=True),
    sa.Column('memory_limit', sa.String(length=30), nullable=True),
    sa.Column('storage_size', sa.String(length=30), nullable=True),
    sa.Column('config_maps', sa.JSON(), nullable=True),
    sa.Column('secret_refs', sa.JSON(), nullable=True),
    sa.Column('helm_values', sa.JSON(), nullable=True),
    sa.Column('deploy_strategy', sa.String(length=30), nullable=True),
    sa.Column('max_unavailable', sa.String(length=20), nullable=True),
    sa.Column('max_surge', sa.String(length=20), nullable=True),
    sa.Column('approval_required', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_id', 'environment_name', name='uq_application_environment')
    )
    with op.batch_alter_table('application_environments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_application_environments_application_id'), ['application_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_application_environments_environment_name'), ['environment_name'], unique=False)

    op.create_table('application_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('config_group_id', sa.String(length=36), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('environment_id', sa.Integer(), nullable=False),
    sa.Column('config_type', sa.String(length=30), nullable=False),
    sa.Column('config_key', sa.String(length=253), nullable=False),
    sa.Column('encrypted_value', sa.Text(), nullable=True),
    sa.Column('value_format', sa.String(length=20), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_secret', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('changed_by', sa.String(length=120), nullable=False),
    sa.Column('change_message', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['environment_id'], ['application_environments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('application_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_application_configs_application_id'), ['application_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_application_configs_config_group_id'), ['config_group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_application_configs_config_type'), ['config_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_application_configs_environment_id'), ['environment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_application_configs_is_active'), ['is_active'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_application_configs_is_active'))
        batch_op.drop_index(batch_op.f('ix_application_configs_environment_id'))
        batch_op.drop_index(batch_op.f('ix_application_configs_config_type'))
        batch_op.drop_index(batch_op.f('ix_application_configs_config_group_id'))
        batch_op.drop_index(batch_op.f('ix_application_configs_application_id'))

    op.drop_table('application_configs')
    with op.batch_alter_table('application_environments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_application_environments_environment_name'))
        batch_op.drop_index(batch_op.f('ix_application_environments_application_id'))

    op.drop_table('application_environments')
    # ### end Alembic commands ###
